function varargout = finalgui_fit(varargin)
%{
Created by: Chris Cadonic
=======================================
This function handles the user interface for fitting the model. The
user can start Qubist, and contrast how varying the parameters
of the model affects the output of the model with experimental
data. The user may also load new data to fit, and so on.

The instantiation code and object creation code are generated by
GUIDE in matlab. The remaining code was written specifically to
allow functionality in the program and is specific to the model.
GUIDE was primarily used for the interface, and to lay out elements
All Callback functions were programmed manually for use in this
model.
%}

% Last Modified by GUIDE v2.5 09-Feb-2015 12:53:55

%% Initialization Code
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @main_gui_OpeningFcn, ...
    'gui_OutputFcn',  @main_gui_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


%% GUI Creation code
% --- Executes just before main_gui is made visible.
function main_gui_OpeningFcn(hObject, eventdata, handles, varargin)

% Choose default command line output for main_gui
handles.output = hObject;

% get the location of the current directory
handles.curdir = fileparts(which(mfilename));

%take in the setup parameters from the 'finalgui.m' function
if ~isempty(varargin)
    handles.parameters = varargin{1};
    
    which_fit = {'Fitting: Control Data', 'Fitting: Experimental Data'};
    
    set(handles.fitting_data_text, 'String', ...
        which_fit{handles.parameters.data_fitting});
    
    handles.ctrlParams = varargin{1}.ctrlParams;
    handles.expParams = varargin{1}.expParams;
    
    % get all the data into the handles structure
    handles.data = varargin{2};
    
    %cell array for whether fitting ctrl or Alz data
    handles.data.data_types = {'CtrlO2', 'AlzO2', 'CtrlOCR', 'AlzOCR'};
    
end

%store the default data for the model
for param=1:numel(handles.parameters.paramNames)
    handles.initialData.(handles.parameters.paramNames{param}) = ...
        handles.ctrlParams.(handles.parameters.paramNames{param});
end

%store all graph handles in the handles structure as an array
[handles.graphs{1:2}] = deal(handles.O2_plot,handles.OCR_plot);

%label the axes for all graphs
graphLabel(handles);

% %store all control editing text boxes in the handles structure as an array
% [handles.allcontEdits{1:9}] = deal(handles.V_max_cedit, handles.K_1_cedit, ...
%     handles.K_m_cedit,handles.fV_Vmax_cedit,handles.fV_K_cedit, handles.fV_Km_cedit, ...
%     handles.f0_Vmax_cedit, handles.f0_Km_cedit, handles.Dh_cedit);
%
%store all exp editing text boxes in the handles structure as an array
[handles.allEdits{1:9}] = deal(handles.fIV_Vmax_edit, handles.fIV_K_edit, ...
    handles.fIV_Km_edit,handles.fV_Vmax_edit,handles.fV_K_edit, handles.fV_Km_edit, ...
    handles.f0_Vmax_edit, handles.f0_Km_edit, handles.Dh_edit);
%
% %store all initial concentrations text boxes in the handles structure as an
% %array
% [handles.allInitials{1:5}] = deal(handles.initial_cytctot_edit, ...
%     handles.initial_cytcox_edit, handles.initial_cytcred_edit, ...
%     handles.initial_o2_edit, handles.initial_hn_edit);


%
% %insert the initial parameter values into the control and experimental textboxes
% setParams(handles,handles.initialData,'control');
% setParams(handles,handles.initialData,'experimental');
%
% %insert the initial concentration values into the textboxes
% handles = setInitials(handles, [handles.parameters.cytctot, ...
%     handles.parameters.cytcox, handles.parameters.cytcred, ...
%     handles.parameters.O2, handles.parameters.Hn, ...
%     handles.parameters.Hp]);

guidata(hObject,handles);

% --- Outputs from this function are returned to the command line.
function varargout = main_gui_OutputFcn(hObject, eventdata, handles)
% Get default command line output from handles structure
varargout{1} = handles.output;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Main Callback Functions

function finalgui_fit_WindowKeyPressFcn(hObject, eventdata, handles)
% Keypressfcn for the entire GUI
switch eventdata.Key
    case {'p','return'}
        plot_Callback(hObject,eventdata,handles);
    case 'r'
        randomizeButton_Callback(hObject,eventdata,handles);
    case 'd'
        params_default_Callback(hObject,eventdata,handles);
    case 'e'
        initial_default_Callback(hObject,eventdata,handles);
    case 'o'
        optimize_Callback(hObject, eventdata, handles);
    case 'l'
        loadparams_Callback(hObject, eventdata, handles);
end

function optimize_Callback(hObject, eventdata, handles) %optimize button

%run Qubist for optimization
launchQubist

function initial_cytctot_edit_Callback(hObject,eventdata,handles)
editBox(hObject,handles,'initial','Cytctot');

%get current total Cyt C
currTot = str2double(get(hObject,'String'));
newCytcred = 0;

while ~(newCytcred)
    takeVal = inputdlg(['What will be the initial value of Cyt C ', ...
        'reduced? The remaining value from the total amount of ', ...
        'Cytochrome C will be set as Cyt C oxidized. The New value ', ...
        'of Cytochrome C Total: ',num2str(currTot),'.'], ...
        'Set Cytochrome Cyt C reduced');
    newCytcred = ensureRightInput(str2double(takeVal{1}),currTot);
end
newCytcox = currTot - newCytcred;

%update the values in boxes and parameters structure
set(handles.initial_cytcox_edit,'String',num2str(newCytcox));
handles.parameters.Cytcox = newCytcox;
set(handles.initial_cytcred_edit,'String',num2str(newCytcred));
handles.parameters.Cytcred = newCytcred;
guidata(hObject,handles);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Edit boxes for Initial conditions and Parameters

function initial_cytcox_edit_Callback(hObject,eventdata,handles)
handles = editBox(hObject,handles,'initial','Cytcox');
guidata(hObject,handles);

function initial_cytcred_edit_Callback(hObject,eventdata,handles)
handles = editBox(hObject,handles,'initial','Cytcred');
guidata(hObject,handles);

function initial_o2_edit_Callback(hObject,eventdata,handles)
handles = editBox(hObject,handles,'initial','O2');
guidata(hObject,handles);

function initial_hn_edit_Callback(hObject,eventdata,handles)
handles = editBox(hObject,handles,'initial','Hn');
guidata(hObject,handles);

function initial_ph_edit_Callback(hObject,eventdata,handles)
getHpconc = 0;
oldHp = 0;
newHp = 0;
getVal = str2double(get(hObject,'String'));

if isnan(getVal) %if not, throw error box and reset value
    msgbox('Please input a valid number.','Not a number');
    
    %get the concentration value for resetting the edit box
    getHpconc = getfield(handles.parameters,'Hp');
    
    oldHp = -log10(getHpconc *1E-6);
    
    set(hObject,'String',oldHp);
else %if so, then update the model with new value
    %Hp from the given pH
    if checkpH(getVal)
        newHp = (10^-getVal) * 1E9;
        handles.parameters = setfield(handles.parameters,'Hp',newHp);
    else
        %get the concentration value for resetting the edit box
        getHpconc = getfield(handles.parameters,'Hp');
        
        oldHp = -log10(getHpconc *1E-9);
        set(hObject,'String',oldHp);
    end
end

guidata(hObject,handles);

function V_max_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','Vmax');
guidata(hObject,handles);

function K_1_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','K1');
guidata(hObject,handles);

function K_m_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','Km');
guidata(hObject,handles);

function p1_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','p1');
guidata(hObject,handles);

function p2_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','p2');
guidata(hObject,handles);

function p3_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','p3');
guidata(hObject,handles);

function f0Vmax_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','f0Vmax');
guidata(hObject,handles);

function f0Km_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','f0Km');
guidata(hObject,handles);

function Dh_cedit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'control','Dh');
guidata(hObject,handles);

function V_max_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','Vmax');
guidata(hObject,handles);

function K_1_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','K1');
guidata(hObject,handles);

function K_m_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','Km');
guidata(hObject,handles);

function p1_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','p1');
guidata(hObject,handles);

function p2_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','p2');
guidata(hObject,handles);

function p3_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','p3');
guidata(hObject,handles);

function f0Vmax_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','f0Vmax');
guidata(hObject,handles);

function f0Km_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','f0Km');
guidata(hObject,handles);

function Dh_edit_Callback(hObject, eventdata, handles)
handles = editBox(hObject,handles,'experimental','Dh');
guidata(hObject,handles);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Additional buttons
%function for randomizing initial conditions
function randomizeButton_Callback(hObject,eventdata,handles)
%generate random vector
randomVect = randn(1,5)*25+100; % 4 initial conditions
randomVect(3) = randn*0.0033+0.01; % set cyt c red very very low initially
randomVect(1) = randomVect(2) + randomVect(3); % set cyt c tot to ox + red
randomVect(6) = (10^-(randn*1+7))*1E6; % randomize a pH

%send these values to set Initials to change boxes and parameters
handles = setInitials(handles, randomVect, 'randomize');
guidata(hObject,handles);

%function for resetting initial concentrations
function initial_default_Callback(hObject,eventdata,handles)
handles = setInitials(handles, handles.initialData(1:6), 'setDefault');
guidata(hObject,handles);

%function for resetting initial parameters
function params_default_Callback(hObject, eventdata, handles)
handles = setParams(handles, handles.initialData(7:end), ...
    'control','setDefault');
handles = setParams(handles, handles.initialData(7:end),  ...
    'experimental','setDefault');
guidata(hObject,handles);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Menu Callback functions
%save the current version of fig
function save_fig_Callback(hObject, eventdata, handles)
%save the image and color map for the overall window
image = getframe(gcf);

try
    %save the image to a file specified by the user
    [filename,filepath]=uiputfile(fullfile(handles.curdir,'StateImages', ...
        [date,'-FitFigureImage.png']),'Save screenshot file');
    imwrite(image.cdata,[filepath,filename]);
    
    disp(['Image was successfully saved to: ', filepath,filename]);
catch % if an error is caught, don't throw error and instead abort save image
    disp('Snapshot save operation aborted.');
end

%save just the figures
function save_graphs_Callback(hObject, eventdata, handles)
% save the image and color map for the overall window
image = getframe(gcf);

%top_left = ginput(1);
%bot_right = ginput(1);

% crop just the graphs and store that as the image
image = imcrop(image.cdata,[565,79,817,685]);

try
    %save the image to a file specified by the user
    [filename,filepath]=uiputfile(fullfile(handles.curdir,'StateImages', ...
        [date,'-FitsessionImage.png']),'Save image of graphs to file');
    imwrite(image,[filepath,filename]);
    
    disp(['Image was successfully saved to: ', filepath,filename]);
catch % if an error is caught, don't throw error and instead abort save image
    disp('Saving image of graphs aborted.');
end

%save the workspace
function save_session_Callback(hObject,eventdata,handles)
%turn off 'use uisave' warning since uisave is in fact being used
warning('off','MATLAB:Figure:FigureSavedToMATFile');

try
    % save the current data found in the model
    currentdata = getappdata(gcf);
    [filename,filepath]=uiputfile(fullfile(handles.curdir,'Savestates', ...
        [date,'-FitSaveSession.mat']), 'Save session file');
    uisave('currentdata',[filepath,filename]);
    
    disp(['Session was successfully saved session file to: ', filepath,filename]);
catch % if an error is caught, don't throw error and instead abort save session
    disp('Session save operation aborted.');
end

%load a saved workspace
function load_session_Callback(hObject,eventdata,handles)
try
    [filename,filepath]=uigetfile(fullfile(handles.curdir,'Savestates','*.mat'), ...
        'Load session file');
    close(gcf);
    load([filepath,filename]);
    
    % check if it was a valid session file
    if (exist('currentdata'))
        disp('Session successfully loaded.');
    else % if not, reload finalgui to reset the GUI
        disp('.mat chosen was not a correct session savestate. Resetting GUI now.');
        finalgui_fit(handles.parameters);
    end
catch % if an error is caught, reload finalgui to reset the GUI
    disp('Session load operation aborted. Resetting GUI now.');
    finalgui_fit(handles.parameters);
end

function exit_prog_Callback(hObject, eventdata, handles)
disp('Goodbye! Thank you for using my mitochondrial model!');
close;

function version_Callback(hObject, eventdata, handles)
try
    [~,ver]=system('git describe --abbrev=0');
    msgbox(['The current version of this code is ',ver(1:end-1),'.'],'Code Version');
catch
    mshbox('To check the code version, "git" is required.','Git not found');
end

function info_Callback(hObject,eventdata, handles)
cd ..; % go up one directory level
open('README.md'); %open the readme file
cd DeterministicModel; % Re-enter DeterministicModel directory

function save_graph_Callback(hObject, eventdata, handles)
%output the figure to be saved
newgraph = openGraph('save');

%acquire the desired name for the figure
[figname,figpath]=uiputfile('.png','Please save the figure file.');

%save figure into fig file pointed out by the user
if ischar(figname) %check if user selected an output name
    set(newgraph,'color','w');
    export_fig(newgraph,[figpath,figname]);
else %if not, then abort saving and provide message
    msgbox('No output file name provided.','Operation aborted.');
end
%close the figure to free memory
close(newgraph);

function open_graph_Callback(hObject, eventdata, handles)
openGraph; %simply open the figure in a new window

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Plot Graphs Callback
function plot_Callback(hObject, eventdata, handles) %plot button in gui

%store variables for differntiating control and experimental parameter sets
params = handles.ctrlParams;

%clear all axes graphs using arrayfun to distribute cla to each axes
arrayfun(@cla,findall(0,'type','axes'))

%plug in the equations into the ode solver
[t,y] = solver(handles.parameters,params, handles.data);

%store the values calculated for each variable
[cytcred, o2, Hn, Hp] = deal(y(:,1),y(:,2),y(:,3),y(:,4));

%calculate the OCR values from the oxygen
calcOCR = calculateOCR(handles,cytcred,o2,Hn,Hp,'control');
calcOCR = calcOCR * -1000;

%plot the O2 concentration over time with real O2 data on top
axes(handles.O2_plot);
hold on
plot(t(2:end),handles.data.(handles.data.data_types{...
    handles.parameters.data_fitting})(2:end),'red', ...
    'lineWidth',2);
plot(t(2:end),o2(2:end),'black','lineWidth',2);
hold off

%plot the OCR over time with real OCR data on top
axes(handles.OCR_plot);
hold on
plot(t(2:end),handles.data.(handles.data.data_types{...
    handles.parameters.data_fitting+2})(2:end),'red', ...
    'lineWidth',2);
plot(t(2:end),calcOCR(2:end),'black','lineWidth',2);
hold off

%add vertical lines to all graphs for injection times
for graph = 1:numel(handles.graphs)
    axes(handles.graphs{graph});
    vertScale = get(gca,'yLim'); % get the y resolution
    vertRange = [vertScale(1), vertScale(end)*0.98];
    
    % draw oligo line
    line([handles.parameters.oligoTimes(1), handles.parameters.oligoTimes(1)], ...
        vertRange, 'Color','b','LineWidth',0.01);
    text(handles.parameters.oligoTimes(1),vertRange(end)*1.005,'Oligomycin', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    
    % draw fccp lines
    line([handles.parameters.fccp_25_t, handles.parameters.fccp_25_t], vertRange,'Color','b');
    text(handles.parameters.fccp_25_t,vertRange(end)*1.005,'FCCP_{125}', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    line([handles.parameters.fccp_50_t, handles.parameters.fccp_50_t],vertRange,'Color','b');
    text(handles.parameters.fccp_50_t,vertRange(end)*1.005,'FCCP_{250}', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    line([handles.parameters.fccp_75_t, handles.parameters.fccp_75_t], vertRange,'Color','b');
    text(handles.parameters.fccp_75_t,vertRange(end)*1.005,'FCCP_{375}', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    line([handles.parameters.fccp_100_t, handles.parameters.fccp_100_t], vertRange,'Color','b');
    text(handles.parameters.fccp_100_t,vertRange(end)*1.005,'FCCP_{500}', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    
    % draw inhibit line
    line([handles.parameters.inhibitTimes(1), handles.parameters.inhibitTimes(1)], ...
        vertRange, 'Color','b');
    text(handles.parameters.inhibitTimes(1),vertRange(end)*1.005,'Rot/AA', ...
        'FontSize',6,'HorizontalAlignment','center','Color','b');
    
    % while iterating over graphs, also set xLim
    set(gca,'xLim',[t(1), t(end)]);
    
end

%update all the graph axes
graphLabel(handles);

guidata(hObject,handles);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Graph Labeling Function
function graphLabel(handles)
%{
since updating the axes elements resets the axis properties such as title,
this function is called each time a figure is plotted so as to reset the
titles and labels to the proper text.
%}
for i=1:numel(handles.graphs)
    axes(handles.graphs{i})
    set(handles.graphs{i},'FontSize',8);
    xlabel(handles.parameters.xlab,'FontName','Helvetica','FontSize',8);
    ylabel(handles.parameters.ylab{i+1},'FontName','Helvetica','FontSize',8);
    title(textwrap({handles.parameters.title{i+1}},30), ...
        'FontWeight','bold','FontName','Helvetica','FontSize',9);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Load Previous Solutions Button
function loadparams_Callback(hObject,eventdata,handles)

%open dialog for user to navigate to file
[filename,filepath] = uigetfile(fullfile(handles.curdir, ...
    'Solutions','*-BestResults.mat'),['Select the "BestResults.mat"', ...
    'containing the parameter set to load']);

if ischar(filename) %if a file is selected, load that file
    load([filepath,filename]); %load the file
    
    values = [];
    
    for j=1:1:length(fieldnames(bestSet))-1
        values(j) = bestSet.(handles.parameters.paramNames{j});
    end
    
    %change all the values of parameters to loaded parameter set
    handles = setParams(handles,values','control','changeVals');
    %additional argin signals setParams to update handles.parameters
    guidata(hObject,handles);
else
    disp('No file selected. Load parameters operation aborted.');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Open Clicked Figure in New Figure
function varargout = openGraph(varargin)
%determine which object was clicked
whichgraph = gco;
obj=get(gca);
% set(whichgraph,'DefaultPlotFontSize',16);

%open a new figure using the graph from the relevant axes
h2copy = allchild(whichgraph); %extract all children from hObject
if isempty(h2copy) %check to see if the graph exists yet
    msgbox(['This function has not been plotted yet. Please use the ', ...
        'plot button below to graph the function before opening it.'],'No Plot');
else
    if ~isempty(varargin)
        % create the figure
        newgraph = figure('Visible','Off','units','normalized','outerposition',[0 0 1 1]);
    else
        % create the figure
        newgraph = figure('units','normalized','outerposition',[0 0 1 1]); %create the figure
    end
    hParent = axes; %create handle for axes child
    copyobj(h2copy,hParent) %copy the original graph to the new fig
    
    %now add the correct labels to the new figure
    xlabel(obj.XLabel.String,'FontName','Calibri','FontSize',16);
    ylabel(obj.YLabel.String,'FontName','Calibri','FontSize',16);
    title(obj.Title.String,'FontSize',22,'FontWeight','bold','FontName','Calibri');
    
    %change the children to change the reagent text sizes
    textChildren = findobj(hParent,'FontSize',6); % get the text objects
    set(textChildren,'FontSize',12); % increase their font size
    
    %optionally output the figure for the 'save' feature
    varargout{1}=newgraph;
    
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Change all parameter values
function handles = setParams(handles,values,type,varargin)
%insert the parameter values passed to the function in the GUI

%check for whether it is control or experimental parameters
if strcmp(type,'control')
    boxes = handles.allcontEdits;
    params = handles.ctrlParams;
else
    boxes = handles.allEdits;
    params = handles.expParams;
end

%change all the values in the correct params struc if vargin nonempty
if ~isempty(varargin)
    boxes = [boxes {handles.initial_cytcox_edit handles.initial_cytcred_edit}];
    [params.fIV_Vmax, params.fIV_K, params.fIV_Km, params.fV_Vmax, params.fV_K, params.fV_Km, ...
        params.f0_Vmax, params.f0_Km, params.Dh, params.cytcox, params.cytcred] ...
        = deal(values(1), values(2), values(3), values(4), values(5), ...
        values(6),values(7),values(8), values(9), values(10), values(11));
end

%loop over and change all the displayed values for the parameters
for i = 1:numel(boxes)
    boxes{i}.String = values(i);
end

if strcmp(type,'control')
    handles.ctrlParams = params;
else
    handles.expParams = params;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Change all Initial values
function handles = setInitials(handles,values,varargin)
%insert the parameter values passed to the function in the GUI

%loop over and change all the displayed values for the parameters
for i = 1:numel(handles.allInitials)
    set(handles.allInitials{i},'String',values(i));
end

%calc pH from concentration and set the proper text box to it
setpH=-log10(values(6)*1E-6);
set(handles.initial_ph_edit,'String',setpH);

%change all the values in the handles.parameters struc if vargin nonempty
if ~isempty(varargin)
    [handles.parameters.Cytctot, handles.parameters.Cytcox, ...
        handles.parameters.Cytcred, handles.parameters.O2, ...
        handles.parameters.Hn, handles.parameters.Hp] = deal( ...
        values(1), values(2), values(3), values(4), values(5), values(6));
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Edit text box
function handles = editBox(hObject,handles,type,paramChange)
%extract the new value input by the user
newVal = str2double(get(hObject, 'String'));

if strcmp(type,'control')
    %check for whether or not a correct input was given
    if isnan(newVal) %if not, throw error box and reset value
        msgbox('Please input a valid number.','Not a number');
        set(hObject,'String',getfield(handles.ctrlParams,paramChange));
    else %if so, then update the model with new value
        handles.ctrlParams = setfield(handles.ctrlParams,paramChange,newVal);
    end
elseif strcmp(type,'experimental')
    %check for whether or not a correct input was given
    if isnan(newVal) %if not, throw error box and reset value
        msgbox('Please input a valid number.','Not a number');
        set(hObject,'String',getfield(handles.expParams,paramChange));
    else %if so, then update the model with new value
        handles.expParams = setfield(handles.expParams,paramChange,newVal);
    end
else
    %check for whether or not a correct input was given
    if isnan(newVal) %if not, throw error box and reset value
        msgbox('Please input a valid number.','Not a number');
        set(hObject,'String',getfield(handles.parameters,paramChange));
    else %if so, then update the model with new value
        handles.parameters = setfield(handles.parameters,paramChange,newVal);
    end
end

%also check to see if cytochrome c total needs to be updated
if strcmp(paramChange,'Cytcred')|strcmp(paramChange,'Cytcox')
    %update the total amount of cytochrome c total
    handles = updateInitialCytctot(hObject,handles);
    guidata(hObject,handles);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Update Initial Cytchrome C Total
function handles = updateInitialCytctot(hObject,handles)
%get current total cyt c
newCytcox = str2double(get(handles.initial_cytcox_edit,'String'));
newCytcred = str2double(get(handles.initial_cytcred_edit,'String'));
newTot = newCytcox + newCytcred;

%increase cyt c tot by the amount of introduced cyt c red
set(handles.initial_cytctot_edit,'String',newCytcox+newCytcred);
handles.parameters.Cytctot = newTot;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Quick function for calculating OCR from o2
function ocr = calculateOCR(handles,cytcred,o2,Hn,Hp,type)

% check whether this calculation is for control or experimental parameters
if strcmp(type,'control')
    params = handles.ctrlParams;
else
    params = handles.expParams;
end

ocr = (-1/2).*((params.fIV_Vmax.*o2)./(params.fIV_Km.*(1+(params.fIV_K./cytcred))+o2)).*Hn./Hp;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Check for input value
function cytcred = ensureRightInput(input,currTot)
if ~isnumeric(input)
    msgbox('Not a valid number. Please enter a number.','Not a number');
else
    if input > currTot
        waitfor(msgbox(['Please enter a number less than the ', ...
            'total amount of Cytochrome C. That is, less than ', ...
            num2str(currTot),'.'], 'Cytochrome C reduced level too high'));
        cytcred = 0;
    else
        cytcred = input;
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Check for valid pH value
function validity = checkpH(value)
validity = true;
if (value < 0) || (value > 14)
    waitfor(msgbox('Not a valid pH.','Invalid pH'));
    validity = false;
end
